In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

print(df.shape)

df.head()

(7043, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [2]:
# Check for missing values
print(df.dtypes)
print()
print("Missing Values:", df.isnull().sum())
print("Duplicates:", df['customerID'].duplicated().sum())

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

Missing Values: customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64
Duplicates: 0

In [3]:
# TotalCharges fix
bad = pd.to_numeric(df['TotalCharges'], errors='coerce').isnull()

print("Bad Values:", bad.sum())

df.loc[bad, ['customerID', 'tenure', 'MonthlyCharges', 'TotalCharges', 'Churn']]

Bad Values: 11

      customerID  tenure  MonthlyCharges TotalCharges Churn
488   4472-LVYGI       0           52.55                 No
753   3115-CZMZD       0           20.25                 No
936   5709-LVOEQ       0           80.85                 No
1082  4367-NUYAO       0           25.75                 No
1340  1371-DWPAZ       0           56.05                 No
3331  7644-OMVMY       0           19.85                 No
3826  3213-VVOLG       0           25.35                 No
4380  2520-SGTTA       0           20.00                 No
5218  2923-ARZLG       0           19.70                 No
6670  4075-WKNIU       0           73.35                 No
6754  2775-SEFEE       0           61.90                 No

In [4]:
# Clean Data

# Convert TotalCharges to numeric
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'] = df['TotalCharges'].fillna(0)

# Drop CustomerID column
df = df.drop('customerID', axis=1)

# Convert target to binary
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

print("TotalCharges type:", df['TotalCharges'].dtype)
print("Shape:", df.shape)
print()
print(df['Churn'].value_counts())

TotalCharges type: float64
Shape: (7043, 20)

Churn
0    5174
1    1869
Name: count, dtype: int64

In [5]:
# How churn varies by contract type
print(df.groupby('Contract')['Churn'].mean().round(3))
print()

# By InternetService
print(df.groupby('InternetService')['Churn'].mean().round(3))
print()

# Average tenure churners vs non-churners
print(df.groupby('Churn')['tenure'].mean().round(1))
print()

# Average MonthlyCharges churners vs non-churners
print(df.groupby('Churn')['MonthlyCharges'].mean().round(2))

Contract
Month-to-month    0.427
One year          0.113
Two year          0.028
Name: Churn, dtype: float64

InternetService
DSL            0.190
Fiber optic    0.419
No             0.074
Name: Churn, dtype: float64

Churn
0    37.6
1    18.0
Name: tenure, dtype: float64

Churn
0    61.27
1    74.44
Name: MonthlyCharges, dtype: float64

In [6]:
# Convert text columns to numeric
df_encoded = pd.get_dummies(df, drop_first=True)

print(df_encoded.shape)

(7043, 31)

In [7]:
#Split the data into training and testing sets

from sklearn.model_selection import train_test_split

X = df_encoded.drop('Churn', axis=1)
y = df_encoded['Churn']

# 80/20 split for training and testing
X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Second split
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.25, random_state=42, stratify=y_temp)
                                                  

print("Train:", X_train.shape)
print("Validation:", X_val.shape)
print("Test:", X_test.shape)

Train: (4225, 30)
Validation: (1409, 30)
Test: (1409, 30)

In [8]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

print("Scaled")

Scaled

In [9]:
# Logistic Regression Model

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

lr = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)
lr.fit(X_train_scaled, y_train)

lr_pred = lr.predict(X_val_scaled)

print("Accuracy:", accuracy_score(y_val, lr_pred))
print()
print("Confusion Matrix:\n", confusion_matrix(y_val, lr_pred))
print()
print("Classification Report:\n", classification_report(y_val, lr_pred))

Accuracy: 0.7459190915542938

Confusion Matrix:
 [[756 279]
 [ 79 295]]

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.73      0.81      1035
           1       0.51      0.79      0.62       374

    accuracy                           0.75      1409
   macro avg       0.71      0.76      0.72      1409
weighted avg       0.80      0.75      0.76      1409

In [10]:
# Random Forest Model

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
rf.fit(X_train_scaled, y_train)

rf_pred = rf.predict(X_val_scaled)

print("Accuracy:", accuracy_score(y_val, rf_pred))
print()
print("Confusion Matrix:\n", confusion_matrix(y_val, rf_pred))
print()
print("Classification Report:\n", classification_report(y_val, rf_pred))

Accuracy: 0.7877927608232789

Confusion Matrix:
 [[941  94]
 [205 169]]

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.91      0.86      1035
           1       0.64      0.45      0.53       374

    accuracy                           0.79      1409
   macro avg       0.73      0.68      0.70      1409
weighted avg       0.77      0.79      0.77      1409

In [11]:
# Gradient Boosting Model

from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier(random_state=42)
gb.fit(X_train_scaled, y_train)

gb_pred = gb.predict(X_val_scaled)

print("Accuracy:", accuracy_score(y_val, gb_pred))
print()
print("Confusion Matrix:\n", confusion_matrix(y_val, gb_pred))
print()
print("Classification Report:\n", classification_report(y_val, gb_pred))

Accuracy: 0.8034066713981547

Confusion Matrix:
 [[947  88]
 [189 185]]

Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.91      0.87      1035
           1       0.68      0.49      0.57       374

    accuracy                           0.80      1409
   macro avg       0.76      0.70      0.72      1409
weighted avg       0.79      0.80      0.79      1409

In [12]:
import pickle
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42))
])

pipeline.fit(X_train, y_train)

# Evaluate the best model on the test set

test_pred = pipeline.predict(X_test)

print("TEST RESULTS")
print("Accuracy:", accuracy_score(y_test, test_pred))
print()
print("Confusion Matrix:\n", confusion_matrix(y_test, test_pred))
print()
print("Classification Report:\n", classification_report(y_test, test_pred))

# Save the model to a file
with open('churn_model.pkl', 'wb') as f:
    pickle.dump(pipeline, f)

print("Model Saved to pkl")

TEST RESULTS
Accuracy: 0.7402413058907026

Confusion Matrix:
 [[750 285]
 [ 81 293]]

Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.72      0.80      1035
           1       0.51      0.78      0.62       374

    accuracy                           0.74      1409
   macro avg       0.70      0.75      0.71      1409
weighted avg       0.80      0.74      0.75      1409

Model Saved to pkl

In [13]:
print(list(X_train.columns))

['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges', 'gender_Male', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes', 'MultipleLines_No phone service', 'MultipleLines_Yes', 'InternetService_Fiber optic', 'InternetService_No', 'OnlineSecurity_No internet service', 'OnlineSecurity_Yes', 'OnlineBackup_No internet service', 'OnlineBackup_Yes', 'DeviceProtection_No internet service', 'DeviceProtection_Yes', 'TechSupport_No internet service', 'TechSupport_Yes', 'StreamingTV_No internet service', 'StreamingTV_Yes', 'StreamingMovies_No internet service', 'StreamingMovies_Yes', 'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes', 'PaymentMethod_Credit card (automatic)', 'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check']

In [14]:
%pip install --force-reinstall --no-cache-dir "sagemaker>=2,<3"

Collecting sagemaker<3,>=2
  Downloading sagemaker-2.257.6-py3-none-any.whl.metadata (19 kB)
Collecting attrs<26,>=24 (from sagemaker<3,>=2)
  Downloading attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting boto3<2.0,>=1.42.2 (from sagemaker<3,>=2)
  Downloading boto3-1.43.73-py3-none-any.whl.metadata (6.6 kB)
Collecting cloudpickle>=2.2.1 (from sagemaker<3,>=2)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting docker (from sagemaker<3,>=2)
  Downloading docker-7.2.0-py3-none-any.whl.metadata (3.8 kB)
Collecting fastapi (from sagemaker<3,>=2)
  Downloading fastapi-0.141.1-py3-none-any.whl.metadata (27 kB)
Collecting google-pasta (from sagemaker<3,>=2)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting graphene<4,>=3 (from sagemaker<3,>=2)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting importlib-metadata<7.0,>=1.4.0 (from sagemaker<3,>=2)
  Downloading importlib_metadata-6.11.0-py3-none-any.whl.metadata (4.9 kB)
Collecting jsonschema (from sagemaker<3,>=2)
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting numpy<3.0,>=1.26.4 (from sagemaker<3,>=2)
  Downloading numpy-2.5.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting omegaconf<3,>=2.2 (from sagemaker<3,>=2)
  Downloading omegaconf-2.3.1-py3-none-any.whl.metadata (4.5 kB)
Collecting packaging<25,>=23.0 (from sagemaker<3,>=2)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pandas>=2.3.0 (from sagemaker<3,>=2)
  Downloading pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting pathos (from sagemaker<3,>=2)
  Downloading pathos-0.3.5-py3-none-any.whl.metadata (11 kB)
Collecting platformdirs (from sagemaker<3,>=2)
  Downloading platformdirs-4.11.3-py3-none-any.whl.metadata (5.5 kB)
Collecting protobuf<7.0,>=3.12 (from sagemaker<3,>=2)
  Downloading protobuf-6.33.6-cp39-abi3-manylinux2014_x86_64.whl.metadata (593 bytes)
Collecting psutil (from sagemaker<3,>=2)
  Downloading psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl.metadata (22 kB)
Collecting pytz (from sagemaker<3,>=2)
  Downloading pytz-2026.3.post1-py2.py3-none-any.whl.metadata (22 kB)
Collecting pyyaml>=6.0.1 (from sagemaker<3,>=2)
  Downloading pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting requests (from sagemaker<3,>=2)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting sagemaker-core<2.0.0,>=1.0.71 (from sagemaker<3,>=2)
  Downloading sagemaker_core-1.0.78-py3-none-any.whl.metadata (4.9 kB)
Collecting schema (from sagemaker<3,>=2)
  Downloading schema-0.7.8-py2.py3-none-any.whl.metadata (34 kB)
Collecting smdebug-rulesconfig==1.0.1 (from sagemaker<3,>=2)
  Downloading smdebug_rulesconfig-1.0.1-py2.py3-none-any.whl.metadata (943 bytes)
Collecting tblib<4,>=1.7.0 (from sagemaker<3,>=2)
  Downloading tblib-3.2.2-py3-none-any.whl.metadata (27 kB)
Collecting tqdm (from sagemaker<3,>=2)
  Downloading tqdm-4.70.0-py3-none-any.whl.metadata (57 kB)
Collecting urllib3<3.0.0,>=1.26.8 (from sagemaker<3,>=2)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting uvicorn (from sagemaker<3,>=2)
  Downloading uvicorn-0.52.3-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore<1.44.0,>=1.43.73 (from boto3<2.0,>=1.42.2->sagemaker<3,>=2)
  Downloading botocore-1.43.73-py3-none-any.whl.metadata (5.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2.0,>=1.42.2->sagemaker<3,>=2)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.20.0,>=0.19.0 (from boto3<2.0,>=1.42.2->sagemaker<3,>=2)
  Downloading s3transfer-0.19.2-py3-none-any.whl.metadata (1.7 kB)
Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.44.0,>=1.43.73->boto3<2.0,>=1.42.2->sagemaker<3,>=2)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting graphql-core<3.3,>=3.1 (from graphene<4,>=3->sagemaker<3,>=2)
  Downloading graphql_core-3.2.11-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4,>=3->sagemaker<3,>=2)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Collecting typing-extensions<5,>=4.7.1 (from graphene<4,>=3->sagemaker<3,>=2)
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting zipp>=0.5 (from importlib-metadata<7.0,>=1.4.0->sagemaker<3,>=2)
  Downloading zipp-4.1.0-py3-none-any.whl.metadata (3.6 kB)
Collecting antlr4-python3-runtime==4.9.* (from omegaconf<3,>=2.2->sagemaker<3,>=2)
  Downloading antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1->botocore<1.44.0,>=1.43.73->boto3<2.0,>=1.42.2->sagemaker<3,>=2)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting pydantic<3.0.0,>=2.0.0 (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2)
  Downloading pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Collecting rich<15.0.0,>=13.0.0 (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2)
  Downloading rich-14.3.4-py3-none-any.whl.metadata (18 kB)
Collecting mock<5.0,>4.0 (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2)
  Downloading mock-4.0.3-py3-none-any.whl.metadata (2.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema->sagemaker<3,>=2)
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema->sagemaker<3,>=2)
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema->sagemaker<3,>=2)
  Downloading rpds_py-2026.6.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2)
  Downloading annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.4 (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2)
  Downloading pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2)
  Downloading typing_inspection-0.4.4-py3-none-any.whl.metadata (2.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2)
  Downloading pygments-2.21.0-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3,>=2)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting charset_normalizer<4,>=2 (from requests->sagemaker<3,>=2)
  Downloading charset_normalizer-3.5.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (45 kB)
Collecting idna<4,>=2.5 (from requests->sagemaker<3,>=2)
  Downloading idna-3.19-py3-none-any.whl.metadata (9.2 kB)
Collecting certifi>=2023.5.7 (from requests->sagemaker<3,>=2)
  Downloading certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Collecting starlette>=0.46.0 (from fastapi->sagemaker<3,>=2)
  Downloading starlette-1.6.0-py3-none-any.whl.metadata (6.4 kB)
Collecting annotated-doc>=0.0.2 (from fastapi->sagemaker<3,>=2)
  Downloading annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
Collecting anyio<5,>=3.6.2 (from starlette>=0.46.0->fastapi->sagemaker<3,>=2)
  Downloading anyio-4.14.2-py3-none-any.whl.metadata (4.6 kB)
Collecting ppft>=1.7.8 (from pathos->sagemaker<3,>=2)
  Downloading ppft-1.7.8-py3-none-any.whl.metadata (12 kB)
Collecting dill>=0.4.1 (from pathos->sagemaker<3,>=2)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting pox>=0.3.7 (from pathos->sagemaker<3,>=2)
  Downloading pox-0.3.7-py3-none-any.whl.metadata (8.0 kB)
Collecting multiprocess>=0.70.19 (from pathos->sagemaker<3,>=2)
  Downloading multiprocess-0.70.19-py312-none-any.whl.metadata (7.5 kB)
Collecting click>=7.0 (from uvicorn->sagemaker<3,>=2)
  Downloading click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting h11>=0.8 (from uvicorn->sagemaker<3,>=2)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Downloading sagemaker-2.257.6-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 101.1 MB/s  0:00:00
Downloading smdebug_rulesconfig-1.0.1-py2.py3-none-any.whl (20 kB)
Downloading attrs-25.4.0-py3-none-any.whl (67 kB)
Downloading boto3-1.43.73-py3-none-any.whl (140 kB)
Downloading botocore-1.43.73-py3-none-any.whl (15.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.7/15.7 MB 191.7 MB/s  0:00:00
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Downloading graphql_core-3.2.11-py3-none-any.whl (214 kB)
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading importlib_metadata-6.11.0-py3-none-any.whl (23 kB)
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading numpy-2.5.2-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 148.6 MB/s  0:00:00
Downloading omegaconf-2.3.1-py3-none-any.whl (79 kB)
Downloading packaging-24.2-py3-none-any.whl (65 kB)
Downloading protobuf-6.33.6-cp39-abi3-manylinux2014_x86_64.whl (323 kB)
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Downloading s3transfer-0.19.2-py3-none-any.whl (90 kB)
Downloading sagemaker_core-1.0.78-py3-none-any.whl (444 kB)
Downloading jsonschema-4.26.0-py3-none-any.whl (90 kB)
Downloading mock-4.0.3-py3-none-any.whl (28 kB)
Downloading platformdirs-4.11.3-py3-none-any.whl (23 kB)
Downloading pydantic-2.13.4-py3-none-any.whl (472 kB)
Downloading pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 107.2 MB/s  0:00:00
Downloading pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (807 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.9/807.9 kB 398.3 MB/s  0:00:00
Downloading rich-14.3.4-py3-none-any.whl (310 kB)
Downloading pygments-2.21.0-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 313.1 MB/s  0:00:00
Downloading tblib-3.2.2-py3-none-any.whl (12 kB)
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading annotated_types-0.8.0-py3-none-any.whl (13 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Downloading markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 129.8 MB/s  0:00:00
Downloading referencing-0.37.0-py3-none-any.whl (26 kB)
Downloading rpds_py-2026.6.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (366 kB)
Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Downloading typing_inspection-0.4.4-py3-none-any.whl (14 kB)
Downloading zipp-4.1.0-py3-none-any.whl (10 kB)
Downloading docker-7.2.0-py3-none-any.whl (148 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.5.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (248 kB)
Downloading idna-3.19-py3-none-any.whl (68 kB)
Downloading certifi-2026.7.22-py3-none-any.whl (136 kB)
Downloading fastapi-0.141.1-py3-none-any.whl (131 kB)
Downloading annotated_doc-0.0.5-py3-none-any.whl (5.3 kB)
Downloading starlette-1.6.0-py3-none-any.whl (75 kB)
Downloading anyio-4.14.2-py3-none-any.whl (125 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
Downloading pathos-0.3.5-py3-none-any.whl (82 kB)
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
Downloading multiprocess-0.70.19-py312-none-any.whl (150 kB)
Downloading pox-0.3.7-py3-none-any.whl (29 kB)
Downloading ppft-1.7.8-py3-none-any.whl (56 kB)
Downloading psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl (155 kB)
Downloading pytz-2026.3.post1-py2.py3-none-any.whl (508 kB)
Downloading schema-0.7.8-py2.py3-none-any.whl (19 kB)
Downloading tqdm-4.70.0-py3-none-any.whl (80 kB)
Downloading uvicorn-0.52.3-py3-none-any.whl (79 kB)
Downloading click-8.4.2-py3-none-any.whl (119 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Building wheels for collected packages: antlr4-python3-runtime
  Building wheel for antlr4-python3-runtime (pyproject.toml) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144590 sha256=1935465b4df8eff153e4339490d3d4c83ad5e126092666e6b23ce92fc5f3c832
  Stored in directory: /tmp/pip-ephem-wheel-cache-q30klwew/wheels/1f/be/48/13754633f1d08d1fbfc60d5e80ae1e5d7329500477685286cd
Successfully built antlr4-python3-runtime
Installing collected packages: schema, pytz, antlr4-python3-runtime, zipp, urllib3, typing-extensions, tqdm, tblib, smdebug-rulesconfig, six, rpds-py, pyyaml, pygments, psutil, protobuf, ppft, pox, platformdirs, packaging, numpy, mock, mdurl, jmespath, idna, h11, graphql-core, dill, cloudpickle, click, charset_normalizer, certifi, attrs, annotated-types, annotated-doc, uvicorn, typing-inspection, requests, referencing, python-dateutil, pydantic-core, omegaconf, multiprocess, markdown-it-py, importlib-metadata, graphql-relay, google-pasta, anyio, starlette, rich, pydantic, pathos, pandas, jsonschema-specifications, graphene, docker, botocore, s3transfer, jsonschema, fastapi, boto3, sagemaker-core, sagemaker
  Attempting uninstall: schema
    Found existing installation: schema 0.7.8
    Uninstalling schema-0.7.8:
      Successfully uninstalled schema-0.7.8
  Attempting uninstall: pytz
    Found existing installation: pytz 2026.3.post1
    Uninstalling pytz-2026.3.post1:
      Successfully uninstalled pytz-2026.3.post1
  Attempting uninstall: antlr4-python3-runtime━━━━━━━━━━━  1/62 [pytz]
    Found existing installation: antlr4-python3-runtime 4.9.32m 1/62 [pytz]
    Uninstalling antlr4-python3-runtime-4.9.3:━━━━━━━  1/62 [pytz]
      Successfully uninstalled antlr4-python3-runtime-4.9.3[32m 1/62 [pytz]
  Attempting uninstall: zipp━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/62 [antlr4-python3-runtime]
    Found existing installation: zipp 4.1.0━━━━━━━━━━━━━━━━━━━  2/62 [antlr4-python3-runtime]
    Uninstalling zipp-4.1.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/62 [antlr4-python3-runtime]
      Successfully uninstalled zipp-4.1.0━━━━━━━━━━━━━━━━━━━━━  2/62 [antlr4-python3-runtime]
  Attempting uninstall: urllib3━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/62 [antlr4-python3-runtime]
    Found existing installation: urllib3 2.7.0━━━━━━━━━━━━━━━━  2/62 [antlr4-python3-runtime]
    Uninstalling urllib3-2.7.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/62 [antlr4-python3-runtime]
      Successfully uninstalled urllib3-2.7.0━━━━━━━━━━━━━━━━━━  2/62 [antlr4-python3-runtime]
  Attempting uninstall: typing-extensions━━━━━━━━━━━━━━━━━━━━━━━━━  4/62 [urllib3]n3-runtime]
    Found existing installation: typing_extensions 4.16.0━━━━━  4/62 [urllib3]
    Uninstalling typing_extensions-4.16.0:━━━━━━━━━━━━━━━━━━━━  4/62 [urllib3]
      Successfully uninstalled typing_extensions-4.16.0━━━━━━━━━━━  5/62 [typing-extensions]
  Attempting uninstall: tqdm━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/62 [typing-extensions]
    Found existing installation: tqdm 4.70.0━━━━━━━━━━━━━━━━━━  5/62 [typing-extensions]
    Uninstalling tqdm-4.70.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/62 [typing-extensions]
      Successfully uninstalled tqdm-4.70.0━━━━━━━━━━━━━━━━━━━━  5/62 [typing-extensions]
  Attempting uninstall: tblibm━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/62 [tqdm]tensions]
    Found existing installation: tblib 3.2.2━━━━━━━━━━━━━━━━━━  6/62 [tqdm]
    Uninstalling tblib-3.2.2:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/62 [tqdm]
      Successfully uninstalled tblib-3.2.2━━━━━━━━━━━━━━━━━━━━  6/62 [tqdm]
  Attempting uninstall: smdebug-rulesconfig━━━━━━━━━━━━━━━━━━━  6/62 [tqdm]
    Found existing installation: smdebug-rulesconfig 1.0.1━━━━  6/62 [tqdm]
    Uninstalling smdebug-rulesconfig-1.0.1:━━━━━━━━━━━━━━━━━━━  6/62 [tqdm]
      Successfully uninstalled smdebug-rulesconfig-1.0.1━━━━━━  6/62 [tqdm]
  Attempting uninstall: six━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/62 [tqdm]
    Found existing installation: six 1.17.0━━━━━━━━━━━━━━━━━━━  6/62 [tqdm]
    Uninstalling six-1.17.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  6/62 [tqdm]
      Successfully uninstalled six-1.17.0━━━━━━━━━━━━━━━━━━━━━━━━━  9/62 [six]
  Attempting uninstall: rpds-py━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/62 [six]
    Found existing installation: rpds-py 2026.6.3━━━━━━━━━━━━━  9/62 [six]
    Uninstalling rpds-py-2026.6.3:━━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/62 [six]
      Successfully uninstalled rpds-py-2026.6.3━━━━━━━━━━━━━━━  9/62 [six]
  Attempting uninstall: pyyaml━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/62 [six]
    Found existing installation: PyYAML 6.0.3━━━━━━━━━━━━━━━━━  9/62 [six]
    Uninstalling PyYAML-6.0.3:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  9/62 [six]
      Successfully uninstalled PyYAML-6.0.3━━━━━━━━━━━━━━━━━━━  9/62 [six]
  Attempting uninstall: pygments0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/62 [pyyaml]
    Found existing installation: Pygments 2.21.0━━━━━━━━━━━━━━ 11/62 [pyyaml]
    Uninstalling Pygments-2.21.0:m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/62 [pygments]
      Successfully uninstalled Pygments-2.21.0━━━━━━━━━━━━━━━━ 12/62 [pygments]
  Attempting uninstall: psutil[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/62 [pygments]
    Found existing installation: psutil 7.2.2━━━━━━━━━━━━━━━━━ 12/62 [pygments]
    Uninstalling psutil-7.2.2:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/62 [pygments]
      Successfully uninstalled psutil-7.2.2━━━━━━━━━━━━━━━━━━━ 12/62 [pygments]
  Attempting uninstall: protobuf90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/62 [psutil]
    Found existing installation: protobuf 6.33.6━━━━━━━━━━━━━━ 13/62 [psutil]
    Uninstalling protobuf-6.33.6:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/62 [psutil]
      Successfully uninstalled protobuf-6.33.6━━━━━━━━━━━━━━━━ 13/62 [psutil]
  Attempting uninstall: ppft[0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14/62 [protobuf]
    Found existing installation: ppft 1.7.8━━━━━━━━━━━━━━━━━━━ 14/62 [protobuf]
    Uninstalling ppft-1.7.8:[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14/62 [protobuf]
      Successfully uninstalled ppft-1.7.8━━━━━━━━━━━━━━━━━━━━━ 14/62 [protobuf]
  Attempting uninstall: pox━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14/62 [protobuf]
    Found existing installation: pox 0.3.7━━━━━━━━━━━━━━━━━━━━━━━━ 16/62 [pox]]
    Uninstalling pox-0.3.7:m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16/62 [pox]
      Successfully uninstalled pox-0.3.7━━━━━━━━━━━━━━━━━━━━━━ 16/62 [pox]
  Attempting uninstall: platformdirs━━━━━━━━━━━━━━━━━━━━━━━━━━ 16/62 [pox]
    Found existing installation: platformdirs 4.11.3━━━━━━━━━━ 16/62 [pox]
    Uninstalling platformdirs-4.11.3:━━━━━━━━━━━━━━━━━━━━━━━━━ 16/62 [pox]
      Successfully uninstalled platformdirs-4.11.3━━━━━━━━━━━━ 16/62 [pox]
  Attempting uninstall: packaging━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16/62 [pox]
    Found existing installation: packaging 24.2━━━━━━━━━━━━━━━ 16/62 [pox]
    Uninstalling packaging-24.2:m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16/62 [pox]
      Successfully uninstalled packaging-24.2━━━━━━━━━━━━━━━━━ 16/62 [pox]
  Attempting uninstall: numpy━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/62 [packaging]

In [15]:
import numpy as np
import pandas as pd
import sagemaker
from sagemaker import get_execution_role

session = sagemaker.Session()
role = get_execution_role()
bucket = session.default_bucket()
prefix = 'sagemaker/telco-churn'


df_sm = pd.concat([df_encoded['Churn'], df_encoded.drop(columns=['Churn'])], axis=1)
df_sm = df_sm.astype(float)

shuffled = df_sm.sample(frac=1, random_state=42).reset_index(drop=True)
split_at = int(0.8 * len(shuffled))
train_sm = shuffled.iloc[:split_at]
val_sm = shuffled.iloc[split_at:]

train_sm.to_csv('train.csv', header=False, index=False)
val_sm.to_csv('validation.csv', header=False, index=False)

train_s3 = session.upload_data('train.csv', bucket=bucket, key_prefix=f'{prefix}/train')
val_s3 = session.upload_data('validation.csv', bucket=bucket, key_prefix=f'{prefix}/val')

print("Uploaded to:", bucket)
print("Shape:", train_sm.shape)

sagemaker.config INFO - Fetched defaults config from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/sagemaker-user/.config/sagemaker/config.yaml
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3Bucket
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3ObjectKeyPrefix
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3Bucket
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3ObjectKeyPrefix
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3Bucket
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3ObjectKeyPrefix
Uploaded to: amazon-sagemaker-365698175161-us-east-2-cu2ccb8aeza2sp
Shape: (5634, 31)

In [18]:
from sagemaker import image_uris
from sagemaker.inputs import TrainingInput
from sagemaker.estimator import Estimator

container = image_uris.retrieve('linear-learner', session.boto_region_name)

session_clean = sagemaker.Session(sagemaker_config={"SchemaVersion": "1.0"})

estimator = Estimator(
    image_uri=container,
    role=role,
    instance_count=1,
    instance_type='ml.m5.large',
    output_path=f's3://{bucket}/{prefix}/output',
    sagemaker_session=session_clean
)

estimator.set_hyperparameters(
    feature_dim=30,
    predictor_type='binary_classifier',
    mini_batch_size=100,
    binary_classifier_model_selection_criteria='f_beta',
    target_recall=0.8
)

s3_train = TrainingInput(s3_data=train_s3, content_type='text/csv')
s3_val = TrainingInput(s3_data=val_s3, content_type='text/csv')

estimator.fit({'train': s3_train, 'validation': s3_val})

predictor = estimator.deploy(initial_instance_count=1, instance_type='ml.m5.large')

print("Deployed Successfully")

2026-08-18 07:18:44 Starting - Starting the training job...
2026-08-18 07:19:16 Downloading - Downloading input data......
2026-08-18 07:20:01 Downloading - Downloading the training image.........
2026-08-18 07:21:32 Training - Training image download completed. Training in progress.Docker entrypoint called with argument(s): train
Running default environment configuration script
[08/18/2026 07:21:36 INFO 140442078832448] Reading default configuration from /opt/amazon/lib/python3.8/site-packages/algorithm/resources/default-input.json: {'mini_batch_size': '1000', 'epochs': '15', 'feature_dim': 'auto', 'use_bias': 'true', 'binary_classifier_model_selection_criteria': 'accuracy', 'f_beta': '1.0', 'target_recall': '0.8', 'target_precision': '0.8', 'num_models': 'auto', 'num_calibration_samples': '10000000', 'init_method': 'uniform', 'init_scale': '0.07', 'init_sigma': '0.01', 'init_bias': '0.0', 'optimizer': 'auto', 'loss': 'auto', 'margin': '1.0', 'quantile': '0.5', 'loss_insensitivity': '0.01', 'huber_delta': '1.0', 'num_classes': '1', 'accuracy_top_k': '3', 'wd': 'auto', 'l1': 'auto', 'momentum': 'auto', 'learning_rate': 'auto', 'beta_1': 'auto', 'beta_2': 'auto', 'bias_lr_mult': 'auto', 'bias_wd_mult': 'auto', 'use_lr_scheduler': 'true', 'lr_scheduler_step': 'auto', 'lr_scheduler_factor': 'auto', 'lr_scheduler_minimum_lr': 'auto', 'positive_example_weight_mult': '1.0', 'balance_multiclass_weights': 'false', 'normalize_data': 'true', 'normalize_label': 'auto', 'unbias_data': 'auto', 'unbias_label': 'auto', 'num_point_for_scaler': '10000', '_kvstore': 'auto', '_num_gpus': 'auto', '_num_kv_servers': 'auto', '_log_level': 'info', '_tuning_objective_metric': '', 'early_stopping_patience': '3', 'early_stopping_tolerance': '0.001', '_enable_profiler': 'false'}
[08/18/2026 07:21:36 INFO 140442078832448] Merging with provided configuration from /opt/ml/input/config/hyperparameters.json: {'binary_classifier_model_selection_criteria': 'f_beta', 'feature_dim': '30', 'mini_batch_size': '100', 'predictor_type': 'binary_classifier', 'target_recall': '0.8'}
[08/18/2026 07:21:36 INFO 140442078832448] Final configuration: {'mini_batch_size': '100', 'epochs': '15', 'feature_dim': '30', 'use_bias': 'true', 'binary_classifier_model_selection_criteria': 'f_beta', 'f_beta': '1.0', 'target_recall': '0.8', 'target_precision': '0.8', 'num_models': 'auto', 'num_calibration_samples': '10000000', 'init_method': 'uniform', 'init_scale': '0.07', 'init_sigma': '0.01', 'init_bias': '0.0', 'optimizer': 'auto', 'loss': 'auto', 'margin': '1.0', 'quantile': '0.5', 'loss_insensitivity': '0.01', 'huber_delta': '1.0', 'num_classes': '1', 'accuracy_top_k': '3', 'wd': 'auto', 'l1': 'auto', 'momentum': 'auto', 'learning_rate': 'auto', 'beta_1': 'auto', 'beta_2': 'auto', 'bias_lr_mult': 'auto', 'bias_wd_mult': 'auto', 'use_lr_scheduler': 'true', 'lr_scheduler_step': 'auto', 'lr_scheduler_factor': 'auto', 'lr_scheduler_minimum_lr': 'auto', 'positive_example_weight_mult': '1.0', 'balance_multiclass_weights': 'false', 'normalize_data': 'true', 'normalize_label': 'auto', 'unbias_data': 'auto', 'unbias_label': 'auto', 'num_point_for_scaler': '10000', '_kvstore': 'auto', '_num_gpus': 'auto', '_num_kv_servers': 'auto', '_log_level': 'info', '_tuning_objective_metric': '', 'early_stopping_patience': '3', 'early_stopping_tolerance': '0.001', '_enable_profiler': 'false', 'predictor_type': 'binary_classifier'}
/opt/amazon/lib/python3.8/site-packages/mxnet/model.py:97: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if num_device is 1 and 'dist' not in kvstore:
/opt/amazon/lib/python3.8/site-packages/scipy/optimize/_shgo.py:495: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if cons['type'] is 'ineq':
/opt/amazon/lib/python3.8/site-packages/scipy/optimize/_shgo.py:743: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(self.X_min) is not 0:
[08/18/2026 07:21:39 WARNING 140442078832448] Loggers have already been setup.
[08/18/2026 07:21:39 INFO 140442078832448] Final configuration: {'mini_batch_size': '100', 'epochs': '15', 'feature_dim': '30', 'use_bias': 'true', 'binary_classifier_model_selection_criteria': 'f_beta', 'f_beta': '1.0', 'target_recall': '0.8', 'target_precision': '0.8', 'num_models': 'auto', 'num_calibration_samples': '10000000', 'init_method': 'uniform', 'init_scale': '0.07', 'init_sigma': '0.01', 'init_bias': '0.0', 'optimizer': 'auto', 'loss': 'auto', 'margin': '1.0', 'quantile': '0.5', 'loss_insensitivity': '0.01', 'huber_delta': '1.0', 'num_classes': '1', 'accuracy_top_k': '3', 'wd': 'auto', 'l1': 'auto', 'momentum': 'auto', 'learning_rate': 'auto', 'beta_1': 'auto', 'beta_2': 'auto', 'bias_lr_mult': 'auto', 'bias_wd_mult': 'auto', 'use_lr_scheduler': 'true', 'lr_scheduler_step': 'auto', 'lr_scheduler_factor': 'auto', 'lr_scheduler_minimum_lr': 'auto', 'positive_example_weight_mult': '1.0', 'balance_multiclass_weights': 'false', 'normalize_data': 'true', 'normalize_label': 'auto', 'unbias_data': 'auto', 'unbias_label': 'auto', 'num_point_for_scaler': '10000', '_kvstore': 'auto', '_num_gpus': 'auto', '_num_kv_servers': 'auto', '_log_level': 'info', '_tuning_objective_metric': '', 'early_stopping_patience': '3', 'early_stopping_tolerance': '0.001', '_enable_profiler': 'false', 'predictor_type': 'binary_classifier'}
[08/18/2026 07:21:39 WARNING 140442078832448] Loggers have already been setup.
Process 7 is a worker.
[08/18/2026 07:21:39 INFO 140442078832448] Using default worker.
[08/18/2026 07:21:39 INFO 140442078832448] Checkpoint loading and saving are disabled.
[08/18/2026 07:21:39 INFO 140442078832448] Create Store: local
[08/18/2026 07:21:39 INFO 140442078832448] Scaler algorithm parameters
 <algorithm.scaler.ScalerAlgorithmStable object at 0x7fbab1643e20>
[08/18/2026 07:21:39 INFO 140442078832448] Scaling model computed with parameters:
 {'stdev_label': None, 'stdev_weight':
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[3.7101924e-01 2.4562117e+01 2.9985922e+01 2.2658152e+03 4.9999988e-01
 4.9974170e-01 4.5802334e-01 2.9736289e-01 2.9736289e-01 4.9332482e-01
 4.9674454e-01 4.0920225e-01 4.0920225e-01 4.5293131e-01 4.0920225e-01
 4.7542655e-01 4.0920225e-01 4.7536823e-01 4.0920225e-01 4.5417419e-01
 4.0920225e-01 4.8651078e-01 4.0920225e-01 4.8655301e-01 4.0448236e-01
 4.2533064e-01 4.9173504e-01 4.1254547e-01 4.7142553e-01 4.1921800e-01]
<NDArray 30 @cpu(0)>, 'mean_label': None, 'mean_weight':
[1.6482139e-01 3.2183395e+01 6.4884750e+01 2.2684885e+03 5.0000000e-01
 4.8392856e-01 2.9946429e-01 9.0196431e-01 9.8035723e-02 4.1857135e-01
 4.4303572e-01 2.1267857e-01 2.1267857e-01 2.8821430e-01 2.1267857e-01
 3.4517857e-01 2.1267857e-01 3.4500006e-01 2.1267857e-01 2.9089284e-01
 2.1267857e-01 3.8464275e-01 2.1267857e-01 3.8482139e-01 2.0607136e-01
 2.3714289e-01 5.9053552e-01 2.1750002e-01 3.3339286e-01 2.2750001e-01]
<NDArray 30 @cpu(0)>}
[08/18/2026 07:21:39 INFO 140442078832448] nvidia-smi: took 0.035 seconds to run.
[08/18/2026 07:21:39 INFO 140442078832448] nvidia-smi identified 0 GPUs.
[08/18/2026 07:21:39 INFO 140442078832448] Number of GPUs being used: 0
#metrics {"StartTime": 1787037699.6997788, "EndTime": 1787037699.6998158, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "Meta": "init_train_data_iter"}, "Metrics": {"Total Records Seen": {"sum": 5734.0, "count": 1, "min": 5734, "max": 5734}, "Total Batches Seen": {"sum": 58.0, "count": 1, "min": 58, "max": 58}, "Max Records Seen Between Resets": {"sum": 5634.0, "count": 1, "min": 5634, "max": 5634}, "Max Batches Seen Between Resets": {"sum": 57.0, "count": 1, "min": 57, "max": 57}, "Reset Count": {"sum": 2.0, "count": 1, "min": 2, "max": 2}, "Number of Records Since Last Reset": {"sum": 0.0, "count": 1, "min": 0, "max": 0}, "Number of Batches Since Last Reset": {"sum": 0.0, "count": 1, "min": 0, "max": 0}}}
#metrics {"StartTime": 1787037701.120581, "EndTime": 1787037701.120654, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 0}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.49848979779652186, "count": 1, "min": 0.49848979779652186, "max": 0.49848979779652186}}}
#metrics {"StartTime": 1787037701.1210194, "EndTime": 1787037701.121046, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 1}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.4959391151155744, "count": 1, "min": 0.4959391151155744, "max": 0.4959391151155744}}}
#metrics {"StartTime": 1787037701.1213615, "EndTime": 1787037701.1213815, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 2}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.4912197174344744, "count": 1, "min": 0.4912197174344744, "max": 0.4912197174344744}}}
#metrics {"StartTime": 1787037701.1216705, "EndTime": 1787037701.1216905, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 3}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.48332047087805613, "count": 1, "min": 0.48332047087805613, "max": 0.48332047087805613}}}
#metrics {"StartTime": 1787037701.1219792, "EndTime": 1787037701.1219993, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 4}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.47572554349899293, "count": 1, "min": 0.47572554349899293, "max": 0.47572554349899293}}}
#metrics {"StartTime": 1787037701.1223123, "EndTime": 1787037701.1223328, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 5}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.4753247128214155, "count": 1, "min": 0.4753247128214155, "max": 0.4753247128214155}}}
#metrics {"StartTime": 1787037701.1226244, "EndTime": 1787037701.1226447, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 6}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.47453791413988383, "count": 1, "min": 0.47453791413988383, "max": 0.47453791413988383}}}
#metrics {"StartTime": 1787037701.1229327, "EndTime": 1787037701.122953, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 7}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.4776267085756574, "count": 1, "min": 0.4776267085756574, "max": 0.4776267085756574}}}
#metrics {"StartTime": 1787037701.1232347, "EndTime": 1787037701.1232545, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 8}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.48856272765568326, "count": 1, "min": 0.48856272765568326, "max": 0.48856272765568326}}}
#metrics {"StartTime": 1787037701.1235504, "EndTime": 1787037701.1235707, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 9}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.4999758052825928, "count": 1, "min": 0.4999758052825928, "max": 0.4999758052825928}}}
#metrics {"StartTime": 1787037701.123856, "EndTime": 1787037701.123876, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 10}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.5028928412709918, "count": 1, "min": 0.5028928412709918, "max": 0.5028928412709918}}}
#metrics {"StartTime": 1787037701.1241632, "EndTime": 1787037701.124183, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 11}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.48986652987343926, "count": 1, "min": 0.48986652987343926, "max": 0.48986652987343926}}}
#metrics {"StartTime": 1787037701.1244628, "EndTime": 1787037701.1244826, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 12}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.47138714381626673, "count": 1, "min": 0.47138714381626673, "max": 0.47138714381626673}}}
#metrics {"StartTime": 1787037701.1247728, "EndTime": 1787037701.1247928, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 13}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.4732016168321882, "count": 1, "min": 0.4732016168321882, "max": 0.4732016168321882}}}
#metrics {"StartTime": 1787037701.125078, "EndTime": 1787037701.1250978, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 14}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.47255894660949704, "count": 1, "min": 0.47255894660949704, "max": 0.47255894660949704}}}
#metrics {"StartTime": 1787037701.1253834, "EndTime": 1787037701.1254032, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 15}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.4718011689186096, "count": 1, "min": 0.4718011689186096, "max": 0.4718011689186096}}}
#metrics {"StartTime": 1787037701.1256838, "EndTime": 1787037701.1257033, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 16}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.5219967453820364, "count": 1, "min": 0.5219967453820364, "max": 0.5219967453820364}}}
#metrics {"StartTime": 1787037701.125989, "EndTime": 1787037701.126009, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 17}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.5162018632888794, "count": 1, "min": 0.5162018632888794, "max": 0.5162018632888794}}}
#metrics {"StartTime": 1787037701.1263196, "EndTime": 1787037701.1263409, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 18}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.517185400554112, "count": 1, "min": 0.517185400554112, "max": 0.517185400554112}}}
#metrics {"StartTime": 1787037701.1266284, "EndTime": 1787037701.1266477, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 19}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.5193678092956543, "count": 1, "min": 0.5193678092956543, "max": 0.5193678092956543}}}
#metrics {"StartTime": 1787037701.1269367, "EndTime": 1787037701.1269565, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 20}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.5160482624598912, "count": 1, "min": 0.5160482624598912, "max": 0.5160482624598912}}}
#metrics {"StartTime": 1787037701.1272428, "EndTime": 1787037701.127263, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 21}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.5149440390723092, "count": 1, "min": 0.5149440390723092, "max": 0.5149440390723092}}}
#metrics {"StartTime": 1787037701.127546, "EndTime": 1787037701.127566, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 22}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.5142651162828717, "count": 1, "min": 0.5142651162828717, "max": 0.5142651162828717}}}
#metrics {"StartTime": 1787037701.1278436, "EndTime": 1787037701.127864, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 23}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.5143679748262678, "count": 1, "min": 0.5143679748262678, "max": 0.5143679748262678}}}
#metrics {"StartTime": 1787037701.1281426, "EndTime": 1787037701.1281624, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 24}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.5948610394341605, "count": 1, "min": 0.5948610394341605, "max": 0.5948610394341605}}}
#metrics {"StartTime": 1787037701.1284566, "EndTime": 1787037701.128477, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 25}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.5955589880262102, "count": 1, "min": 0.5955589880262102, "max": 0.5955589880262102}}}
#metrics {"StartTime": 1787037701.128758, "EndTime": 1787037701.1287777, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 26}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.5978090912955147, "count": 1, "min": 0.5978090912955147, "max": 0.5978090912955147}}}
#metrics {"StartTime": 1787037701.129059, "EndTime": 1787037701.129079, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 27}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.5940222726549421, "count": 1, "min": 0.5940222726549421, "max": 0.5940222726549421}}}
#metrics {"StartTime": 1787037701.1293614, "EndTime": 1787037701.1293812, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 28}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.5993017618996757, "count": 1, "min": 0.5993017618996757, "max": 0.5993017618996757}}}
#metrics {"StartTime": 1787037701.1296704, "EndTime": 1787037701.129691, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 29}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.6006238147190639, "count": 1, "min": 0.6006238147190639, "max": 0.6006238147190639}}}
#metrics {"StartTime": 1787037701.129972, "EndTime": 1787037701.129992, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 30}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.600047595841544, "count": 1, "min": 0.600047595841544, "max": 0.600047595841544}}}
#metrics {"StartTime": 1787037701.1303005, "EndTime": 1787037701.1303213, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 31}, "Metrics": {"train_binary_classification_cross_entropy_objective": {"sum": 0.6003152799606323, "count": 1, "min": 0.6003152799606323, "max": 0.6003152799606323}}}
[08/18/2026 07:21:41 INFO 140442078832448] #quality_metric: host=algo-1, epoch=0, train binary_classification_cross_entropy_objective <loss>=0.49848979779652186
#metrics {"StartTime": 1787037702.0018632, "EndTime": 1787037702.0019479, "Dimensions": {"Algorithm": "Linear Learner", "Host": "algo-1", "Operation": "training", "epoch": 0, "model": 0}, "Metrics": {"validation_binary_classification_cross_entropy_objective": {"sum": 0.43122571034157337, "count": 1, "min": 0.43122571034157337, "max": 0.43122571034157337}}}

In [20]:
from sagemaker.serializers import CSVSerializer
from sagemaker.deserializers import JSONDeserializer

predictor.serializer = CSVSerializer()
predictor.deserializer = JSONDeserializer()

sample = val_sm.iloc[0, 1:].values.tolist()
actual = val_sm.iloc[0, 0]

result = predictor.predict(sample)
print("Actual:", actual)
print("Prediction:", result)

Actual: 1.0
Prediction: {'predictions': [{'score': 0.36609625816345215, 'predicted_label': 1}]}

In [22]:
predictor.delete_endpoint()
print("Endpoint deleted")

Endpoint deleted